# SPDX-License-Identifier: GPL-3.0-only

FROM fedora:39

RUN dnf -y update \
    && dnf -y install \
        file \
        htop \
        iputils \
        libvirt-client \
        libvirt-daemon-config-network \
        libvirt-daemon-driver-qemu \
        qemu-system-x86-core \
    && dnf clean all

# avoid "Unable to set XATTR trusted.libvirt.security.dac" error
RUN echo 'remember_owner = 0' >> /etc/libvirt/qemu.conf

# disable libvirt cgroups management, since we're already in a container
RUN echo 'cgroup_controllers = []' >> /etc/libvirt/qemu.conf

COPY domain.xml entrypoint.sh /vm/

# the entrypoint is set in src/create.rs
